---
- name: Add NGINX repository (6.x)
  yum_repository:
    name: nginx
    description: NGINX YUM repo
    baseurl: http://nginx.org/packages/centos/6/$basearch/
    gpgcheck: no
  become: yes
  become_method: sudo

- name: Install nginx
  yum:
    name: nginx
    state: present
  become: yes
  become_method: sudo

- name: Ensure default web directory exists
  file:
    path: /nfs/web/default
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  become: yes
  become_method: sudo

- name: Copy nginx default configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: yes
  become_method: sudo

- name: Start nginx Service
  service: name=nginx state=started enabled=yes
  become: yes
  become_method: sudo
