---
- name: Install HAProxy
  yum:
    name: haproxy
    state: installed
  become: yes
  become_method: sudo

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
  become: yes
  become_method: sudo

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
  become: yes
  become_method: sudo
