# file: mysql/defaults/main.yml

# Basic settings
mysql_root_password: 'password'
mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_datadir: '/var/lib/mysql'

# Cluster settings
percona_master_node: false
wsrep_slave_threads: 8
wsrep_sst_method: xtrabackup-v2
bootstrapping: false  # The task will set this to true if the package is installed on the master node
wsrep_cluster_name: percona-cluster
#wsrep_cluster_hosts: {{ groups.percona_cluster }}
#wsrep_cluster_hosts: ["{{ groups.percona_cluster[0] }}"]
wsrep_sst_username: "sstuser"
wsrep_sst_password: "s3cret"

mysql_log_error: /var/log/mysql/error.log

# Fine Tuning
mysql_key_buffer: '16M'
mysql_max_allowed_packet: '128M'
mysql_thread_stack: '192K'
mysql_cache_size: 8
mysql_max_connections: 100
mysql_table_cache: 64
mysql_query_cache_limit: '1M'
mysql_query_cache_size: '16M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
mysql_mysqldump_max_allowed_packet: '128M'
mysql_isamchk_key_buffer: '16M'

# InnoDB tuning
mysql_innodb_file_per_table: 'innodb_file_per_table'
mysql_innodb_flush_method: 'fdatasync'
mysql_innodb_buffer_pool_size: '128M'
mysql_innodb_flush_log_at_trx_commit: 1
mysql_innodb_lock_wait_timeout: 50
mysql_innodb_log_buffer_size: '1M'
mysql_innodb_log_file_size: '5M'
