---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=installed
  become: yes
  become_method: sudo

- name: Configure NFS (avoid dynamic ports)
  template:
    src: nfs.j2
    dest: /etc/sysconfig/nfs
    mode: 0644
  become: yes
  become_method: sudo
  tags:
    - nfs-config

- name: Ensure rpcbind is running.
  service:
    name: rpcbind
    state: started
    enabled: yes
  become: yes
  become_method: sudo
  tags:
    - nfs-config

- name: Ensure directories to export exist
  file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"
  notify: restart nfs
  become: yes
  become_method: sudo
  tags:
    - nfs-config

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copy
  notify: restart nfs
  become: yes
  become_method: sudo
  tags:
    - nfs-config

- name: Restart NFS immediately if exports are updated.
  service:
    name: nfs
    state: restarted
  when: nfs_exports_copy.changed
  become: yes
  become_method: sudo
  tags:
    - nfs-config

- name: Ensure nfs is running.
  service:
    name: nfs
    state: started
    enabled: yes
  when: nfs_exports|length
  become: yes
  become_method: sudo
